# Generated by Django 4.1.1 on 2023-03-27 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Urun',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ad', models.CharField(max_length=50, verbose_name='Ürünün Adı')),
                ('fiat', models.CharField(max_length=6, verbose_name='Ürünün Fiatı')),
                ('eklendi', models.DateTimeField(auto_now_add=True, verbose_name='Eklendi')),
            ],
        ),
    ]
