# Generated by Django 4.1.1 on 2023-03-27 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='fiat',
            field=models.CharField(default='Ücret Belirtilmedi', max_length=6, verbose_name='Ürünün Fiatı'),
        ),
    ]
