# Generated by Django 4.1.1 on 2023-03-29 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='aciklama',
            field=models.TextField(default='Detay Belirtilmedi...', max_length=200, verbose_name='Ürünün Açıklaması'),
        ),
    ]
