# Generated by Django 4.1.1 on 2023-03-29 09:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0002_urun_aciklama'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='urunQRCode',
            field=models.CharField(max_length=10, null=True, verbose_name='Ürünün QR Kod Numarası'),
        ),
    ]
