# Generated by Django 4.1.1 on 2023-03-29 15:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0002_urun_fiat'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='seriNo',
            field=models.CharField(max_length=7, null=True, verbose_name='Ürünün Seri Numarası'),
        ),
        migrations.AlterField(
            model_name='urun',
            name='fiat',
            field=models.CharField(default='Ücret Belirtilmedi', help_text='Ürünün ücretidir', max_length=6, verbose_name='Ürünün Fiatı'),
        ),
    ]
