# Generated by Django 4.1.1 on 2023-04-03 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0004_alter_urun_urunqrcode'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='resim',
            field=models.FileField(blank=True, null=True, upload_to='uploads', verbose_name='Resim'),
        ),
    ]
