# Generated by Django 4.1.1 on 2023-04-05 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0005_urun_urunresmi'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='garanti',
            field=models.BooleanField(default=False, verbose_name='Garanti'),
        ),
        migrations.AddField(
            model_name='urun',
            name='stokAdet',
            field=models.IntegerField(default=1, verbose_name='Stoktaki Adet Sayısı'),
        ),
    ]
