# Generated by Django 4.1.1 on 2023-04-05 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0006_urun_garanti_urun_stokadet'),
    ]

    operations = [
        migrations.AlterField(
            model_name='urun',
            name='stokAdet',
            field=models.PositiveIntegerField(default=1, verbose_name='Stoktaki Adet Sayısı'),
        ),
    ]
