# Generated by Django 4.1.1 on 2023-04-05 09:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0008_alter_urun_resim'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='garanti',
            field=models.BooleanField(default=True, help_text='Ürünün garantisi', verbose_name='Garantisi Var Mı'),
        ),
        migrations.AddField(
            model_name='urun',
            name='stok',
            field=models.IntegerField(default=1, help_text='Ürünün Stok Sayısı', verbose_name='Stok Sayısı'),
        ),
    ]
