# Generated by Django 4.1.1 on 2023-04-05 17:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0008_yorum'),
    ]

    operations = [
        migrations.AddField(
            model_name='yorum',
            name='product',
            field=models.ForeignKey(default='', on_delete=django.db.models.deletion.CASCADE, to='urunApp.urun', verbose_name='Ürün'),
        ),
    ]
