# Generated by Django 4.1.1 on 2023-04-05 09:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('urunApp', '0009_urun_garanti_urun_stok'),
    ]

    operations = [
        migrations.CreateModel(
            name='Yorumlar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('yazar', models.CharField(max_length=50, verbose_name='Yorumu Yapan Kişi')),
                ('tarih', models.DateTimeField(auto_now_add=True)),
                ('message', models.TextField(max_length=100, verbose_name='Yorum')),
                ('urun', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='urunApp.urun', verbose_name='Ürün')),
            ],
        ),
    ]
