# Generated by Django 4.1.1 on 2023-04-14 16:11

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0010_alter_yorum_product_alter_yorum_yazar'),
    ]

    operations = [
        migrations.AddField(
            model_name='urun',
            name='satici',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Ürünü Satan'),
        ),
    ]
