# Generated by Django 4.1.1 on 2023-04-17 08:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('urunApp', '0012_urun_olusturan'),
    ]

    operations = [
        migrations.CreateModel(
            name='CreditCardAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cardNo', models.CharField(max_length=15, verbose_name='Kart Numarası')),
                ('cardOwner', models.CharField(max_length=20, verbose_name='Kart Sahibi')),
                ('expiredMonthAndYear', models.CharField(max_length=4, verbose_name='Son Kullanım Tarihi')),
                ('cvc', models.CharField(max_length=3, verbose_name='Güvenlik Kodu')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Hesap Sahibi')),
            ],
        ),
    ]
